# Generated by Django 4.1.5 on 2023-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Phone'),
        ),
    ]
